language: go


go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

env:
  - GO111MODULE=on

before_script:
  - go get -tags "reuseport quic kcp zookeeper etcd consul ping rudp utp" -t -v github.com/smallnest/rpcx/...
  - go get github.com/mattn/goveralls

script:
 - go test -tags "reuseport quic kcp zookeeper etcd consul ping rudp utp" -v ./...
 - goveralls -service=travis-ci

notifications:
  email:
    recipients: smallnest@gmail.com
    on_success: change
    on_failure: always