language: go


go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

before_script:
  - go get -u -t -v github.com/smallnest/rpcx/...

script:
 - go test -v ./...
 - goveralls -service=travis-ci

notifications:
  email:
    recipients: smallnest@gmail.com
    on_success: change
    on_failure: always